### ISSUE TITLE
Support BED input? 

### ISSUE THREAD

**Issue by PanZiwei** [BBCG/epialleleR#17]
Hi,
Thanks for the amazing tool. I already have per-site methylation calling results in BED format with chromosome, start position, end position, and methylation status(methlyated/unmethylated) for each CpG site.

Is it possible to use the BED file as epialleleR input for methylation heterogeneity measures analysis? Any hints for the implementation? 

Also, any updates on the https://github.com/BBCG/epialleleR/issues/14?

**Comment by oleksii-nikolaienko** [comment]
Hi and thanks for using :)
As of now, there's no way to supply BED in order to limit `generateCytosineReport` and `generateMhlReport` output. The solutions are (a) to filter their output later or (b) pre-filter BAM file for reads overlapping your BED with `samtools`. And I doubt I will prioritize adding this functionality - because reporting is in general very fast and it's possible to achieve it using `samtools`.
On #14 - will try to dedicate some time after this Christmas. The goal is to have it done before next Bioc release (April), but I hope it won't take that long

**Comment by oleksii-nikolaienko** [comment]
Hi, fyi #14 was completed and closed. Please try out if you are still interested and report any eventual bugs/irregularities.
NB, vignettes and `preprocessBam` help page detail how `G-m` base modifications are treated, although I don't know if BAM file with them can be found in the wild...
